### ISSUE TITLE
conventions & howto

### ISSUE THREAD

**Issue by kockas** [josueeduardo/rest-client#1]
Great job with this fork. Just pointing, that you could somehow differ from original mashape version. The issue is, how you will proceed, when they create 1.4.10 version? It might have functional clash.
I'd propose slight name update (unirested-java) or somehing like that, and start release from 1.0. Or if you plan to make all your contribution inherited from their, make it somehow like 1.1_4_9.1 next 1.1_4_9.2 etc.
Or are you officially successor of their work, and they do not plan to continue?
Thanks.

**Comment by josueeduardo** [comment]
Thanks for your feedback kockas. It seems Mashape is no longer supporting unirest, there are several issues raised there that make me believe it's pretty much inactive. This fork is not intended to be successor of Unirest, but just provide additional features and bug fixes from the original, for those who may find useful. Versioning I will probably be rolled back to 0.1 or something.
Thanks
