### ISSUE TITLE
Multipart file upload doesn't set properly content type

### ISSUE THREAD

**Issue by bitsal** [josueeduardo/rest-client#83]
**Version:** 1.5.0

**Description:**
```
RestClient client = RestClient.builder()
    .defaultHeader('Content-Type', MediaType.APPLICATION_JSON_UTF8_VALUE)
    .build;

def fileStream = new ByteArrayInputStream('test file content'.bytes)

client.post(baseUrl + uri)
         .part('file', fileStream, 'test.png')
         .part('data', toJson(uploadContext), ContentType.APPLICATION_JSON.getMimeType())
         .asString()
```
Target HttpRequest has `application/json` header (default one) instead of correct onr `multipart/form-data;...boundary=...`.
I set default header `application/json` due to almost all of my post payloads are JSON.

**Expected Result:**
Rest client should set a correct content type with a boundary ID to the target request in case of multipart content.

**Current Workaround:**
I create rest client differently for this type of requests without default header.

**Comment by josueeduardo** [comment]
Fixed on 1.6.0. Thanks for letting me know
