### ISSUE TITLE
Any way to set a custom http client?

### ISSUE THREAD

**Issue by jorexe** [josueeduardo/rest-client#84]
I have this warning and i need to change the default http client. Is there a way to do this?

    Invalid cookie header: "Set-Cookie....

**Comment by josueeduardo** [comment]
Currently is not possible to provide your own `HttpClient`, but it's possible to change the internal one by using the RestClient.builder. In this case you change the cookie spec by using
```
RestClient client = RestClient.builder()
                .cookieSpec(CookieSpecs.STANDARD)
                .build()
```

**Comment by jorexe** [comment]
Hi @josueeduardo thank you for you response. I've updated the cookieSpec but i'm still having the log:

    Invalid cookie header: "Set-Cookie: __cfduid=g27abb8ad514971c8ea8f24ee858a1f9d1517842252; expires=Tue, 05-Feb-19 14:50:52 GMT; path=/; domain=.example.com; HttpOnly; Secure". Unrecognized cookie header 'Set-Cookie: __cfduid=g27abb8ad514971c8ea8f24ee858a1f9d1517842252; expires=Tue, 05-Feb-19 14:50:52 GMT; path=/; domain=.example.com; HttpOnly; Secure'

Do you think i need to use another spec?

I only get this log on pr env

Thanks you!

**Comment by josueeduardo** [comment]
@jorexe If the cookie is not in accordance to the selected spec, you will get these messages. 
Your `domain` value must match the origin server domain. So you either update your server to return the appropriate domain, or not set it. Or in cases where your client don't care about cookies (probably not the case) you can use `CookieSpecs.IGNORE_COOKIES`.

**Comment by jorexe** [comment]
I think my domain match the server domain. It's something like https://api.example.com/api/method

Path shouldn't be /api/method right?

**Comment by josueeduardo** [comment]
The path shouldn't be the issue for sure. I tried to replicate the problem, just changing the domain, and I managed to get the cookie stored in the client. The cookie store is entirely managed by the HttpClient, so in case you haven't solved this, I recommend having a look on the [documentation](http://hc.apache.org/httpclient-3.x/cookies.html).

**Comment by jorexe** [comment]
I resolved the issue, it was a sever problem with the domain

Thanks you!
