### ISSUE TITLE
RestClient client = RestClient.newClient().build(); doesn't work?

### ISSUE THREAD

**Issue by davidji99** [josueeduardo/rest-client#90]
Hi there,

According to the README, one can create a new client with `RestClient client = RestClient.newClient().build();`. But for some reason, my IDE (Intellij) complains that `.newClient()` isn't available. I've already `mvn clean install` and such but nothing works. The only method that's available is `.builder()`. Am I missing something super simple here?

(FYI, I'm using v1.6.0 in my pom.xml)

**Comment by josueeduardo** [comment]
Hi.
The README is outdated, sorry about that.
The method name has changed to `builder`. So doing `RestClient client = RestClient.builder().build();` should work.

Also note that you can use the static methods in case you just need a default client:
`Unirest.get()`, `Unirest.post()` and so on.

I will be updating the README when the `1.6.1` gets released.

Thank you
