### ISSUE TITLE
media type application/json ; charset=UTF-8 not recognized

### ISSUE THREAD

**Issue by asafbennatan** [josueeduardo/rest-client#92]
Hi ,
was using unirest but i needed the multi instance feature this library offers ( great addition)
registering Jackson as the object mapper 
`ObjectMappers.register(MediaType.APPLICATION_JSON_TYPE, mapper);
`

will throw an unregistered mapper when the content type received is application/json; charset=utf-8
only when explicitly registering the media type it will work:
```
        MediaType mediaType=MediaType.valueOf("application/json; charset=utf-8");
        ObjectMappers.register(mediaType,mapper);
```

Thanks.

**Comment by joshgontijo** [comment]
Hi, thanks for reporting.
I've fixed it on 6f399ae53c77858af2fc63b6b9240fd560e3c66f.
Available on `1.7.1`
