### ISSUE TITLE
Unirest class can have a double check locking

### ISSUE THREAD

**Issue by thiagomiranda3** [josueeduardo/rest-client#93]
Instead of having a synchronized getClient(). We could use a double check locking:

From:
`private static synchronized RestClient getClient() {
        if (client == null) {
            client = RestClient.builder().build();
        }
        return client;
    }`

To:
`private static RestClient getClient() {
        if (client == null) {
                synchronized (this) {
                        client = RestClient.builder().build();
                }
                return client;
        }
    }`

Or the entirely class could be a Enum, it will become thread safe by default. I could made this modifications if you aprove. It will have a major performance inpact for everyone that uses this class.

**Comment by joshgontijo** [comment]
Hi Thiago, thanks for submitting the issue.

You can find [here](https://rules.sonarsource.com/java/tag/multi-threading/RSPEC-2168) the reasons why is not a good idea to use double lock.
Enum at this stage could potentially break the API depending on how is implemented. The safest alternative is the static holder class approach, which is described in the link as an alternative solution.
Happy to approve if you got time to do so.

Abraco

**Comment by thiagomiranda3** [comment]
I forgot to mention that we need to use volatile on attribute client in order to Double Check become safe. You can see that written on the article of the link you passed to me. After Java 1.5, volatile is completely safe. But I understand if you want to keep this class this way. Because we can use the client builder in order to avoid the synchronized. I only sugested this change because in the original Unirest, we used to use Unirest static methods a lot.

A little about double check in java with volatile:
https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java

**Comment by joshgontijo** [comment]
Fair enough. Either way sounds good. If you got time, please raise a PR, otherwise I can add it to the next release.
